#!/usr/bin/env python3
"""
Dump Unpacker Utility
=====================

This script unpacks the `whatsapp_dump.json` generated by the DevTools scraper.
It extracts the base64 images into a dedicated folder next to the dump file, 
and creates an `extracted_data.json` without modifying the main database.

Usage:
------
Run this script via terminal:
$ python3 scripts/unpack_dump.py --input path/to/whatsapp_dump_1.json
"""
import os
import json
import base64
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Unpack whatsapp_dump.json to a specific folder")
    parser.add_argument('--input', required=True, help="Input whatsapp_dump.json file")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: {input_path} does not exist.")
        return

    # Create output directory based on input filename
    # e.g., backup/whatsapp_dump_1.json -> backup/whatsapp_dump_1/
    output_dir = input_path.parent / input_path.stem
    output_dir.mkdir(parents=True, exist_ok=True)
    
    extracted_json_path = output_dir / "extracted_data.json"

    print(f"Reading dump from {input_path}...")
    with open(input_path, 'r', encoding='utf-8') as f:
        dump_data = json.load(f)

    extracted_entries = []
    processed = 0

    for item in dump_data:
        entry = item['entry']
        base64_str = item['base64'].split(',')[-1]
        
        # Save image
        img_path = output_dir / entry['imageRef']
        try:
            with open(img_path, 'wb') as f:
                f.write(base64.b64decode(base64_str))
        except Exception as e:
            print(f"Failed to save image {img_path}: {e}")
            continue
            
        extracted_entries.append(entry)
        processed += 1

    # Save extracted JSON
    with open(extracted_json_path, 'w', encoding='utf-8') as f:
        json.dump(extracted_entries, f, indent=2, ensure_ascii=False)

    print(f"Successfully unpacked {processed} images to {output_dir}/")
    print(f"Created data file at {extracted_json_path}")
    print("Use the merge script to add these entries to your main data.json.")

if __name__ == '__main__':
    main()
