#!/usr/bin/env python3
"""
Data Merger Utility
===================

This script merges a partial `extracted_data.json` (generated by unpack_dump.py)
into the main `data.json` database.

Key Features:
-------------
1. Deduplication: Ensures only one entry per phone number exists.
2. Date Normalization: Converts dates to ISO format to accurately keep the most recent entry.
3. Path Prefixing (Optional): Allows prepending a folder name to `imageRef` if you plan to keep images in separate subfolders permanently.

Usage:
------
Run this script via terminal:
$ python3 scripts/merge_data.py --input scripts/backup/whatsapp_dump_1/extracted_data.json --main scripts/data.json
"""
import os
import json
import argparse
from datetime import datetime

def normalize_date(date_str):
    if not date_str:
        return ""
    try:
        dt = datetime.strptime(date_str, "%I:%M %p, %m/%d/%Y")
        return dt.isoformat()
    except ValueError:
        pass
    try:
        dt = datetime.strptime(date_str, "%m/%d/%Y, %I:%M %p")
        return dt.isoformat()
    except ValueError:
        pass
    return date_str

def main():
    parser = argparse.ArgumentParser(description="Merge extracted_data.json into main data.json")
    parser.add_argument('--input', required=True, help="Input extracted_data.json file")
    parser.add_argument('--main', default='scripts/data.json', help="Main data.json to update")
    parser.add_argument('--prepend-folder', help="Optional folder prefix to add to imageRef (e.g. 'whatsapp_dump_1/')")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Error: {args.input} does not exist.")
        return

    with open(args.input, 'r', encoding='utf-8') as f:
        new_data = json.load(f)

    main_data = []
    if os.path.exists(args.main):
        with open(args.main, 'r', encoding='utf-8') as f:
            main_data = json.load(f)

    # Convert existing to dict
    data_dict = {item['key']: item for item in main_data}

    merged_count = 0
    updated_count = 0

    for item in new_data:
        # Normalize date for comparison
        item['date'] = normalize_date(item.get('date', ''))
        
        # Strict validation: Only merge valid phone numbers (8+ digits)
        phone = item.get('key', '')
        digits = ''.join(filter(str.isdigit, phone))
        if len(digits) < 8:
            print(f"Skipping invalid/incomplete entry: {phone}")
            continue
            
        if args.prepend_folder:
            # Avoid double prepending
            if not item['imageRef'].startswith(args.prepend_folder):
                item['imageRef'] = os.path.join(args.prepend_folder, item['imageRef'])

        key = phone
        if key in data_dict:
            existing_date = data_dict[key].get('date', '')
            # Compare ISO dates strings
            if item['date'] >= existing_date:
                data_dict[key] = item
                updated_count += 1
        else:
            data_dict[key] = item
            merged_count += 1

    with open(args.main, 'w', encoding='utf-8') as f:
        json.dump(list(data_dict.values()), f, indent=2, ensure_ascii=False)

    print(f"Merge Complete!")
    print(f"- New contacts added: {merged_count}")
    print(f"- Existing contacts updated (newer message): {updated_count}")
    print(f"- Total contacts in {args.main}: {len(data_dict)}")

if __name__ == '__main__':
    main()
